#ifndef TREE_SITTER_ASCIIDOC_TOKENS_H
#define TREE_SITTER_ASCIIDOC_TOKENS_H

#define STR_INCLUDE "include::"
#define STR_IMAGE "image::"
#define STR_IFDEF "ifdef::"
#define STR_IFNDEF "ifndef::"
#define STR_IFEVAL "ifeval::"
#define STR_IFEND "endif::"
#define STR_TAG "tag::"
#define STR_TAGEND "end::"
#define STR_XREF "xref:"
#define STR_FOOTNOTE "footnote:"
#define STR_ANCHOR "anchor:"
#define STR_BTN "btn:"
#define STR_KBD "kbd:"
#define STR_PASS "pass:"
#define STR_ICON "icon:"
#define STR_LINK "link:"
#define STR_MAILTO "mailto:"
#define STR_INDEXTERM "indexterm:"
#define STR_STEM "stem:"
#define STR_LATEXMATH "latexmath:"


#define STR_COMMENT_MARKER "//"
#define STR_BLOCK_COMMENT_SEPARATOR "////"
#define STR_SECTION_HEADER0 "="
#define STR_SECTION_HEADER1 "=="
#define STR_SECTION_HEADER2 "==="
#define STR_SECTION_HEADER3 "===="
#define STR_SECTION_HEADER4 "====="
#define STR_SECTION_HEADER5 "======"
#define STR_BLOCK_EXAMPLE_SEPARATOR1 "===="
#define STR_BLOCK_EXAMPLE_SEPARATOR2 "====="
#define STR_BLOCK_EXAMPLE_SEPARATOR3 "======"

#define STR_BLOCK_LISTING_SEPARATOR "----"
#define STR_BLOCK_LITERAL_SEPARATOR "...."
#define STR_BLOCK_OPEN_SEPARATOR "--"
#define STR_BLOCK_SIDEBAR_SEPARATOR "****"
#define STR_BLOCK_PASSTHROUGH_SEPARATOR "++++"
#define STR_BLOCK_QUOTE_SEPARATOR "____"
#define STR_BLOCK_TABLE_SEPARATOR1 "|==="
#define STR_BLOCK_TABLE_SEPARATOR2 "!==="
#define STR_TABLE_CELL_MARKER1 '|'
#define STR_TABLE_CELL_MARKER2 '!'

#define STR_PAGE_BREAK "<<<"
#define STR_THEMATIC_BREAK1 "---"
#define STR_THEMATIC_BREAK2 "***"

#define STR_ADMONITION_NOTE "NOTE:"
#define STR_ADMONITION_TIP "TIP:"
#define STR_ADMONITION_IMPORTANT "IMPORTANT:"
#define STR_ADMONITION_CAUTION "CAUTION:"
#define STR_ADMONITION_WARNING "WARNING:"

enum TokenType {
  T_TEXT,
  T_WHITESPACE,
  T_NEWLINE,
  T_MONOSPACE_MARKER_START,
  T_MONOSPACE_MARKER_END,
  T_INLINE_PASSTHROUGH_MARKER_START,
  T_INLINE_PASSTHROUGH_MARKER_END,
  T_HARDBREAK,
  T_BLOCK_CONTINUATION,
  T_TITLE_MARKER0,
  T_TITLE_MARKER1,
  T_TITLE_MARKER2,
  T_TITLE_MARKER3,
  T_TITLE_MARKER4,
  T_TITLE_MARKER5,
  T_ATTRIBUTE_MARKER_START,
  T_ATTRIBUTE_MARKER_END,
  T_ATTRIBUTE_MARKER_START_NEG,
  T_ATTRIBUTE_MARKER_END_NEG,
  T_COMMENT_MARKER,
  T_EMPHASIS_MARKER_START,
  T_EMPHASIS_MARKER_END,
  T_STRONG_MARKER_START,
  T_STRONG_MARKER_END,
  T_SUPERSCRIPT_MARKER_START,
  T_SUPERSCRIPT_MARKER_END,
  T_SUBSCRIPT_MARKER_START,
  T_SUBSCRIPT_MARKER_END,
  T_HIGHLIGHT_MARKER_START,
  T_HIGHLIGHT_MARKER_END,

  T_INCLUDE_MARKER,
  T_IMAGE_MARKER,
  T_XREF_MARKER,
  T_FOOTNOTE_MARKER,
  T_ICON_MARKER,
  T_HTTP_MARKER,
  T_LINK_MARKER,
  T_MAILTO_MARKER,

  T_CALLOUT_MARKER_FROM,
  T_CALLOUT_MARKER_TO,
  T_INLINE_OPTION_BLOCK_MARKER_START,
  T_INLINE_OPTION_BLOCK_MARKER_END,
  T_CROSSREFERENCE_MARKER_START,
  T_CROSSREFERENCE_MARKER_END,
  T_CROSSREFERENCE_SPLITTER,
  T_BLOCK_COMMENT_SEPARATOR,
  T_BLOCK_EXAMPLE_SEPARATOR1,
  T_BLOCK_EXAMPLE_SEPARATOR2,
  T_BLOCK_EXAMPLE_SEPARATOR3,
  T_BLOCK_LISTING_SEPARATOR,
  T_BLOCK_LITERAL_SEPARATOR,
  T_BLOCK_OPEN_SEPARATOR,
  T_BLOCK_SIDEBAR_SEPARATOR,
  T_BLOCK_PASSTHROUGH_SEPARATOR,
  T_BLOCK_QUOTE_SEPARATOR,
  T_BLOCK_TABLE_SEPARATOR1,
  T_BLOCK_TABLE_SEPARATOR2,
  T_TABLE_CELL_MARKER,
  T_BLOCK_OPTION_MARKER_START,
  T_BLOCK_OPTION_MARKER_END,
  T_PAGE_BREAK,
  T_THEMATIC_BREAK,
  T_BLOCK_TITLE_MARKER,
  T_EMPTYLINE,
  T_LIST_ASTERISK_MARKER,
  T_LIST_HYPHEN_MARKER,
  T_ADMONITION_NOTE_MARKER,
  T_ADMONITION_TIP_MARKER,
  T_ADMONITION_IMPORTANT_MARKER,
  T_ADMONITION_CAUTION_MARKER,
  T_ADMONITION_WARNING_MARKER,
  T_LIST_DECIMAL__MARKER,
  T_ATTRIBUTE_REFERENCE_START_MARKER,
  T_ATTRIBUTE_REFERENCE_END_MARKER,
  T_TAG_MARKER,
  T_TAG_END_MARKER,
  T_IFDEF_MARKER,
  T_IFEVAL_MARKER,
  T_ENDIF_MARKER,

  T_PASS_MARKER,
  T_STEM_MARKER,
  T_LATEXMATH_MARKER,
  T_PASS_SPLITTER,

};

#endif /* TREE_SITTER_ASCIIDOC_TOKENS_H */
