#ifndef TREE_SITTER_ASCIIDOC_TOKENS_H
#define TREE_SITTER_ASCIIDOC_TOKENS_H
enum TokenType {
  T_TEXT,
  T_WHITESPACE,
  T_NEWLINE,
  T_MONOSPACE_MARKER_START,
  T_MONOSPACE_MARKER_END,
  T_MONOSPACE_UNCONSTRAINED_MARKER_START,
  T_MONOSPACE_UNCONSTRAINED_MARKER_END,
  T_INLINE_PASSTHROUGH_MARKER_START,
  T_INLINE_PASSTHROUGH_MARKER_END,
  T_INLINE_PASSTHROUGH_UNCONSTRAINED_MARKER_START,
  T_INLINE_PASSTHROUGH_UNCONSTRAINED_MARKER_END,
  T_HARDBREAK,
  T_BLOCK_CONTINUATION,
  T_TITLE_MARKER0,
  T_TITLE_MARKER1,
  T_TITLE_MARKER2,
  T_TITLE_MARKER3,
  T_TITLE_MARKER4,
  T_TITLE_MARKER5,
  T_ATTRIBUTE_MARKER_START,
  T_ATTRIBUTE_MARKER_END,
  T_ATTRIBUTE_MARKER_START_NEG,
  T_ATTRIBUTE_MARKER_END_NEG,
  T_COMMENT_MARKER,
  T_EMPHASIS_MARKER_START,
  T_EMPHASIS_MARKER_END,
  T_EMPHASIS_UNCONSTRAINED_MARKER_START,
  T_EMPHASIS_UNCONSTRAINED_MARKER_END,
  T_STRONG_MARKER_START,
  T_STRONG_MARKER_END,
  T_STRONG_UNCONSTRAINED_MARKER_START,
  T_STRONG_UNCONSTRAINED_MARKER_END,
  T_SUPERSCRIPT_MARKER_START,
  T_SUPERSCRIPT_MARKER_END,
  T_SUPERSCRIPT_UNCONSTRAINED_MARKER_START,
  T_SUPERSCRIPT_UNCONSTRAINED_MARKER_END,
  T_SUBSCRIPT_MARKER_START,
  T_SUBSCRIPT_MARKER_END,
  T_SUBSCRIPT_UNCONSTRAINED_MARKER_START,
  T_SUBSCRIPT_UNCONSTRAINED_MARKER_END,
  T_HIGHLIGHT_MARKER_START,
  T_HIGHLIGHT_MARKER_END,
  T_HIGHLIGHT_UNCONSTRAINED_MARKER_START,
  T_HIGHLIGHT_UNCONSTRAINED_MARKER_END,

  T_INCLUDE_MARKER,
  T_IMAGE_MARKER,
  T_IMAGE_INLINE_MARKER,
  T_XREF_MARKER,
  T_FOOTNOTE_MARKER,
  T_ICON_MARKER,
  T_HTTP_MARKER,
  T_LINK_MARKER,
  T_MAILTO_MARKER,

  T_CALLOUT_MARKER_FROM,
  T_CALLOUT_MARKER_TO,



















  T_INLINE_OPTION_BLOCK_MARKER_START,
  T_INLINE_OPTION_BLOCK_MARKER_END,
  T_CROSSREFERENCE_MARKER_START,
  T_CROSSREFERENCE_MARKER_END,
  T_BLOCK_COMMENT_MARKER,
  T_BLOCK_EXAMPLE_SEPARATOR1,
  T_BLOCK_EXAMPLE_SEPARATOR2,
  T_BLOCK_EXAMPLE_SEPARATOR3,
  T_BLOCK_LISTING_SEPARATOR,
  T_BLOCK_LITERAL_SEPARATOR,
  T_BLOCK_OPEN_SEPARATOR,
  T_BLOCK_SIDEBAR_SEPARATOR,
  T_BLOCK_PASSTHROUGH_SEPARATOR,
  T_BLOCK_QUOTE_SEPARATOR,
  T_BLOCK_TABLE_SEPARATOR1,
  T_BLOCK_TABLE_SEPARATOR2,

  T_TABLE_CELL_MARKER1,
  T_TABLE_CELL_MARKER2,

  T_BLOCK_OPTION_MARKER_START,
  T_BLOCK_OPTION_MARKER_END,

  T_PAGE_BREAK,
  T_THEMATIC_BREAK,

  T_BLOCK_TITLE_MARKER,
  T_EMPTYLINE,
  T_LIST_ASTERISK_MARKER,





  T_LIST_HYPHEN_MARKER,

  T_LIST_NUMBERED,





  T_ADMONITION_NOTE_MARKER,
  T_ADMONITION_TIP_MARKER,
  T_ADMONITION_IMPORTANT_MARKER,
  T_ADMONITION_CAUTION_MARKER,
  T_ADMONITION_WARNING_MARKER,

  T_ATTRIBUTE_REFERENCE_START_MARKER,
  T_ATTRIBUTE_REFERENCE_END_MARKER,
  T_TAG_MARKER,
  T_TAG_END_MARKER,
  T_IFDEF_MARKER,

  T_IFEVAL_MARKER,
  T_ENDIF_MARKER,

  T_PASS_MARKER,
  T_STEM_MARKER,
  T_LATEXMATH_MARKER,

  T_DESCRIPTION_LIST_MARKER,

  T_ESCAPE,
};
#endif // TREE_SITTER_ASCIIDOC_TOKENS_H
